// @unocss-include
export const classes = {
  add: "i-material-symbols:add",
  addCircle: "i-material-symbols:add-circle",
  arrowSelectorTool: "i-material-symbols:arrow-selector-tool",
  camera: "i-material-symbols:camera",
  cameraswitch: "i-material-symbols:cameraswitch",
  close: "i-material-symbols:close",
  delete: "i-material-symbols:delete",
  deployedCode: "i-material-symbols:deployed-code",
  deployedCodeSharp: "i-material-symbols:deployed-code-sharp",
  dragIndicator: "i-material-symbols:drag-indicator",
  expandLess: "i-material-symbols:expand-less-rounded",
  expandMore: "i-material-symbols:expand-more-rounded",
  fileMap: "i-material-symbols:file-map",
  lightbulb: "i-material-symbols:lightbulb",
  lightbulbRounded: "i-material-symbols:lightbulb-circle-rounded",
  menu: "i-material-symbols:menu",
  moreVert: "i-material-symbols:more-vert",
  moveSelectionUp: "i-material-symbols:move-selection-up",
  questionMark: "i-material-symbols:question-mark",
  select: "i-material-symbols:select",
  settings: "i-material-symbols:settings",
  square: "i-material-symbols:square",
  squareRounded: "i-material-symbols:square-rounded",
  sunny: "i-material-symbols:sunny",
  transform: "i-material-symbols:transform",
  uploadFile: "i-material-symbols:upload-file",
  visibility: "i-material-symbols:visibility",
  visibilityOff: "i-material-symbols:visibility-off",
  globe: "i-material-symbols:globe",
} as const;

export type IconName = keyof typeof classes;
